name: go-market

services:
  frontend:
    attach: false
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "${HTTP_PORT_FRONTEND}:80"
    depends_on:
      gateway:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--output-document=-", "http://localhost/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - go-market-network

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    environment:
      HTTP_ADDRESS: ":8080"
      CATALOG_GRPC_ADDRESS: "catalog:50051"
      JWT_SECRET: "${JWT_SECRET}"
      JWT_ISSUER: "${JWT_ISSUER}"
      JWT_AUDIENCE: "${JWT_AUDIENCE}"
    ports:
      - "${HTTP_PORT_GATEWAY}:8080"
    depends_on:
      catalog:
        condition: service_started
    networks:
      - go-market-network

  catalog:
    build:
      context: .
      dockerfile: services/catalog/Dockerfile
    environment:
      GRPC_ADDRESS: ":50051"
    ports:
      - "${GRPC_PORT_CATALOG}:50051"
    networks:
      - go-market-network

networks:
  go-market-network:
    driver: bridge
